# NAME: Luke Jung, Justin Jeon
# EMAIL: lukejung@ucla.edu, justinjeon151@gmail.com
# ID: 904982644, 205008698

default:
	gcc -Wall -Wextra -lm lab3a.c -o lab3a
clean:
	rm lab3a *.tar.gz
dist: default
	tar -czvf lab3a-904982644.tar.gz Makefile README lab3a.c ext2_fs.h
